BEGIN;

CREATE TABLE public.p0_default_table_probe (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
CREATE SEQUENCE public.p0_default_sequence_probe;
CREATE FUNCTION public.p0_default_function_probe()
RETURNS boolean
LANGUAGE sql
AS 'SELECT true';

DO $test$
DECLARE
  v_unsafe_defaults text;
BEGIN
  IF has_table_privilege('anon', 'public.p0_default_table_probe', 'SELECT,INSERT,UPDATE,DELETE')
    OR has_table_privilege('authenticated', 'public.p0_default_table_probe', 'SELECT,INSERT,UPDATE,DELETE')
    OR has_table_privilege('service_role', 'public.p0_default_table_probe', 'SELECT,INSERT,UPDATE,DELETE') THEN
    RAISE EXCEPTION 'new public tables inherit application-role privileges';
  END IF;

  IF has_sequence_privilege('anon', 'public.p0_default_sequence_probe', 'USAGE')
    OR has_sequence_privilege('authenticated', 'public.p0_default_sequence_probe', 'USAGE')
    OR has_sequence_privilege('service_role', 'public.p0_default_sequence_probe', 'USAGE') THEN
    RAISE EXCEPTION 'new public sequences inherit application-role privileges';
  END IF;

  IF has_function_privilege('anon', 'public.p0_default_function_probe()', 'EXECUTE')
    OR has_function_privilege('authenticated', 'public.p0_default_function_probe()', 'EXECUTE')
    OR has_function_privilege('service_role', 'public.p0_default_function_probe()', 'EXECUTE') THEN
    RAISE EXCEPTION 'new public functions inherit application-role EXECUTE';
  END IF;

  SELECT string_agg(
    format('%s:%s:%s:%s', owner_role.rolname, defaults.defaclobjtype,
      COALESCE(grantee_role.rolname, 'PUBLIC'), privileges.privilege_type),
    ', '
    ORDER BY owner_role.rolname, defaults.defaclobjtype,
      COALESCE(grantee_role.rolname, 'PUBLIC'), privileges.privilege_type
  )
  INTO v_unsafe_defaults
  FROM pg_default_acl defaults
  JOIN pg_roles owner_role ON owner_role.oid = defaults.defaclrole
  CROSS JOIN LATERAL aclexplode(defaults.defaclacl) privileges
  LEFT JOIN pg_roles grantee_role ON grantee_role.oid = privileges.grantee
  WHERE defaults.defaclnamespace = 'public'::regnamespace
    AND owner_role.rolname = current_user
    AND (
      privileges.grantee = 0
      OR grantee_role.rolname IN ('anon', 'authenticated', 'service_role')
    );

  IF v_unsafe_defaults IS NOT NULL THEN
    RAISE EXCEPTION 'unsafe public default privileges remain: %', v_unsafe_defaults;
  END IF;
END;
$test$;

ROLLBACK;
