-- ============================================================================
-- Aliases expandidos no food_db — cobre lacunas regionais e cotidianas
-- ============================================================================
-- Continuação do seed 20260504210200_food_db_aliases. Adiciona ~65 aliases
-- pra reduzir "0 kcal (sem match TACO)" em pratos comuns que a vision
-- identifica mas o banco não cobria: salgados, fast food, vitaminas,
-- regionais (acarajé, baião, tropeiro), preparações compostas (strogonoff,
-- lasanha, pizza), básicos faltantes (linguiça, salsicha, salada mista).
--
-- Macros aproximados (médias TBCA/TACO/USDA, gramatura por 100g).
-- ============================================================================

DO $$
DECLARE
  v_aliases jsonb := $aliases$[
    {"name_pt":"acarajé","category":"salgados","kcal":265,"prot":13,"carb":21,"fat":15,"fib":4},
    {"name_pt":"coxinha de frango","category":"salgados","kcal":290,"prot":11,"carb":28,"fat":15,"fib":1.5},
    {"name_pt":"coxinha","category":"salgados","kcal":290,"prot":11,"carb":28,"fat":15,"fib":1.5},
    {"name_pt":"esfiha de carne","category":"salgados","kcal":252,"prot":11,"carb":29,"fat":10,"fib":1.5},
    {"name_pt":"esfiha","category":"salgados","kcal":252,"prot":11,"carb":29,"fat":10,"fib":1.5},
    {"name_pt":"pastel de carne","category":"salgados","kcal":340,"prot":12,"carb":26,"fat":21,"fib":1.5},
    {"name_pt":"pastel de queijo","category":"salgados","kcal":345,"prot":11,"carb":27,"fat":22,"fib":1},
    {"name_pt":"pastel","category":"salgados","kcal":340,"prot":12,"carb":26,"fat":21,"fib":1.5},
    {"name_pt":"quibe frito","category":"salgados","kcal":275,"prot":13,"carb":18,"fat":17,"fib":2},
    {"name_pt":"quibe assado","category":"salgados","kcal":215,"prot":14,"carb":17,"fat":11,"fib":2},
    {"name_pt":"quibe","category":"salgados","kcal":275,"prot":13,"carb":18,"fat":17,"fib":2},
    {"name_pt":"empada de frango","category":"salgados","kcal":310,"prot":9,"carb":28,"fat":18,"fib":1},
    {"name_pt":"croquete de carne","category":"salgados","kcal":285,"prot":13,"carb":22,"fat":16,"fib":1},
    {"name_pt":"bolinho de bacalhau","category":"salgados","kcal":250,"prot":15,"carb":18,"fat":13,"fib":1},
    {"name_pt":"enroladinho de salsicha","category":"salgados","kcal":295,"prot":10,"carb":28,"fat":16,"fib":1},
    {"name_pt":"feijão tropeiro","category":"pratos","kcal":190,"prot":9,"carb":24,"fat":7,"fib":4},
    {"name_pt":"baião de dois","category":"pratos","kcal":185,"prot":8,"carb":29,"fat":4,"fib":3.5},
    {"name_pt":"feijoada","category":"pratos","kcal":215,"prot":13,"carb":17,"fat":11,"fib":4},
    {"name_pt":"strogonoff de frango","category":"pratos","kcal":175,"prot":13,"carb":7,"fat":11,"fib":0.5},
    {"name_pt":"strogonoff de carne","category":"pratos","kcal":195,"prot":12,"carb":7,"fat":13,"fib":0.5},
    {"name_pt":"estrogonofe","category":"pratos","kcal":175,"prot":13,"carb":7,"fat":11,"fib":0.5},
    {"name_pt":"lasanha bolonhesa","category":"pratos","kcal":185,"prot":11,"carb":18,"fat":8,"fib":2},
    {"name_pt":"lasanha","category":"pratos","kcal":185,"prot":11,"carb":18,"fat":8,"fib":2},
    {"name_pt":"escondidinho de carne","category":"pratos","kcal":165,"prot":9,"carb":17,"fat":7,"fib":2},
    {"name_pt":"moqueca de peixe","category":"pratos","kcal":110,"prot":12,"carb":4,"fat":5,"fib":1},
    {"name_pt":"frango xadrez","category":"pratos","kcal":150,"prot":15,"carb":8,"fat":7,"fib":1},
    {"name_pt":"frango à parmegiana","category":"pratos","kcal":215,"prot":17,"carb":12,"fat":11,"fib":1},
    {"name_pt":"filé à parmegiana","category":"pratos","kcal":230,"prot":18,"carb":12,"fat":12,"fib":1},
    {"name_pt":"macarrão à bolonhesa","category":"pratos","kcal":155,"prot":7,"carb":21,"fat":4.5,"fib":1.5},
    {"name_pt":"macarrão alho e óleo","category":"pratos","kcal":180,"prot":5,"carb":28,"fat":5,"fib":1},
    {"name_pt":"macarrão ao molho branco","category":"pratos","kcal":175,"prot":6,"carb":22,"fat":7,"fib":1},
    {"name_pt":"pizza de mussarela","category":"pratos","kcal":260,"prot":11,"carb":30,"fat":10,"fib":1.5},
    {"name_pt":"pizza de calabresa","category":"pratos","kcal":280,"prot":12,"carb":28,"fat":13,"fib":1.5},
    {"name_pt":"pizza","category":"pratos","kcal":260,"prot":11,"carb":30,"fat":10,"fib":1.5},
    {"name_pt":"hambúrguer de carne","category":"pratos","kcal":295,"prot":15,"carb":24,"fat":15,"fib":1.5},
    {"name_pt":"x-burger","category":"pratos","kcal":295,"prot":15,"carb":24,"fat":15,"fib":1.5},
    {"name_pt":"x-salada","category":"pratos","kcal":275,"prot":15,"carb":24,"fat":13,"fib":2},
    {"name_pt":"x-bacon","category":"pratos","kcal":325,"prot":17,"carb":24,"fat":18,"fib":1.5},
    {"name_pt":"misto quente","category":"pratos","kcal":285,"prot":14,"carb":28,"fat":13,"fib":1.5},
    {"name_pt":"sanduíche natural","category":"pratos","kcal":195,"prot":10,"carb":22,"fat":7,"fib":2},
    {"name_pt":"sanduíche de frango","category":"pratos","kcal":215,"prot":14,"carb":24,"fat":7,"fib":2},
    {"name_pt":"sanduíche","category":"pratos","kcal":215,"prot":11,"carb":24,"fat":8,"fib":1.5},
    {"name_pt":"crepioca","category":"pratos","kcal":135,"prot":10,"carb":18,"fat":3,"fib":1},
    {"name_pt":"panqueca de frango","category":"pratos","kcal":175,"prot":12,"carb":15,"fat":7,"fib":1},
    {"name_pt":"linguiça toscana","category":"carnes","kcal":290,"prot":15,"carb":1,"fat":25,"fib":0},
    {"name_pt":"linguiça calabresa","category":"carnes","kcal":310,"prot":18,"carb":2,"fat":26,"fib":0},
    {"name_pt":"linguiça","category":"carnes","kcal":290,"prot":15,"carb":1,"fat":25,"fib":0},
    {"name_pt":"salsicha","category":"carnes","kcal":260,"prot":11,"carb":3,"fat":23,"fib":0},
    {"name_pt":"presunto","category":"carnes","kcal":145,"prot":18,"carb":1,"fat":7,"fib":0},
    {"name_pt":"mortadela","category":"carnes","kcal":280,"prot":14,"carb":3,"fat":24,"fib":0},
    {"name_pt":"peito de peru","category":"carnes","kcal":105,"prot":18,"carb":2,"fat":3,"fib":0},
    {"name_pt":"carne moída","category":"carnes","kcal":215,"prot":20,"carb":0,"fat":15,"fib":0},
    {"name_pt":"patinho grelhado","category":"carnes","kcal":175,"prot":28,"carb":0,"fat":7,"fib":0},
    {"name_pt":"picanha grelhada","category":"carnes","kcal":265,"prot":24,"carb":0,"fat":19,"fib":0},
    {"name_pt":"contrafilé","category":"carnes","kcal":210,"prot":25,"carb":0,"fat":12,"fib":0},
    {"name_pt":"costela bovina","category":"carnes","kcal":315,"prot":20,"carb":0,"fat":26,"fib":0},
    {"name_pt":"alcatra grelhada","category":"carnes","kcal":195,"prot":26,"carb":0,"fat":10,"fib":0},
    {"name_pt":"filé mignon grelhado","category":"carnes","kcal":195,"prot":28,"carb":0,"fat":9,"fib":0},
    {"name_pt":"atum em lata","category":"peixes","kcal":120,"prot":26,"carb":0,"fat":1.5,"fib":0},
    {"name_pt":"sardinha em lata","category":"peixes","kcal":210,"prot":24,"carb":0,"fat":12,"fib":0},
    {"name_pt":"tilápia","category":"peixes","kcal":128,"prot":26,"carb":0,"fat":2.7,"fib":0},
    {"name_pt":"merluza grelhada","category":"peixes","kcal":110,"prot":24,"carb":0,"fat":1.3,"fib":0},
    {"name_pt":"camarão grelhado","category":"peixes","kcal":105,"prot":21,"carb":0.5,"fat":1.7,"fib":0},
    {"name_pt":"salada mista","category":"vegetais","kcal":35,"prot":1.5,"carb":6,"fat":0.5,"fib":2.5},
    {"name_pt":"salada verde","category":"vegetais","kcal":18,"prot":1.2,"carb":3,"fat":0.2,"fib":1.8},
    {"name_pt":"salada de tomate","category":"vegetais","kcal":22,"prot":1,"carb":4.5,"fat":0.3,"fib":1.5},
    {"name_pt":"farofa","category":"vegetais","kcal":410,"prot":3,"carb":62,"fat":17,"fib":3.5},
    {"name_pt":"vinagrete","category":"vegetais","kcal":45,"prot":1,"carb":5,"fat":2.5,"fib":1.5},
    {"name_pt":"abobrinha refogada","category":"vegetais","kcal":40,"prot":1.5,"carb":6,"fat":1.5,"fib":2},
    {"name_pt":"abóbora cozida","category":"vegetais","kcal":35,"prot":1.2,"carb":7,"fat":0.2,"fib":1.5},
    {"name_pt":"chuchu cozido","category":"vegetais","kcal":18,"prot":0.9,"carb":4,"fat":0.1,"fib":1.5},
    {"name_pt":"brócolis cozido","category":"vegetais","kcal":25,"prot":2.5,"carb":4,"fat":0.4,"fib":2.5},
    {"name_pt":"couve refogada","category":"vegetais","kcal":40,"prot":3,"carb":4,"fat":2,"fib":3},
    {"name_pt":"vitamina de banana","category":"bebidas","kcal":110,"prot":4,"carb":18,"fat":2.5,"fib":1.5},
    {"name_pt":"smoothie","category":"bebidas","kcal":95,"prot":3,"carb":18,"fat":1.5,"fib":1.5},
    {"name_pt":"suco verde","category":"bebidas","kcal":55,"prot":1.5,"carb":12,"fat":0.3,"fib":1.5},
    {"name_pt":"suco detox","category":"bebidas","kcal":50,"prot":1.2,"carb":11,"fat":0.2,"fib":1.5},
    {"name_pt":"refrigerante","category":"bebidas","kcal":42,"prot":0,"carb":11,"fat":0,"fib":0},
    {"name_pt":"coca-cola","category":"bebidas","kcal":42,"prot":0,"carb":11,"fat":0,"fib":0},
    {"name_pt":"refrigerante zero","category":"bebidas","kcal":1,"prot":0,"carb":0,"fat":0,"fib":0},
    {"name_pt":"chá verde","category":"bebidas","kcal":1,"prot":0,"carb":0,"fat":0,"fib":0},
    {"name_pt":"água de coco","category":"bebidas","kcal":22,"prot":0.5,"carb":4.7,"fat":0.1,"fib":1},
    {"name_pt":"cerveja","category":"bebidas","kcal":43,"prot":0.5,"carb":3.6,"fat":0,"fib":0},
    {"name_pt":"vinho tinto","category":"bebidas","kcal":85,"prot":0.1,"carb":2.6,"fat":0,"fib":0},
    {"name_pt":"caipirinha","category":"bebidas","kcal":175,"prot":0,"carb":15,"fat":0,"fib":0.2},
    {"name_pt":"pamonha","category":"pratos","kcal":175,"prot":3,"carb":30,"fat":5,"fib":2},
    {"name_pt":"aipim","category":"tuberculos","kcal":160,"prot":1.4,"carb":38,"fat":0.3,"fib":1.8},
    {"name_pt":"aipim cozido","category":"tuberculos","kcal":125,"prot":0.8,"carb":30,"fat":0.3,"fib":1.6},
    {"name_pt":"aipim frito","category":"tuberculos","kcal":260,"prot":1.5,"carb":38,"fat":11,"fib":1.8},
    {"name_pt":"polenta","category":"pratos","kcal":85,"prot":2,"carb":17,"fat":1,"fib":1.5},
    {"name_pt":"requeijão","category":"lacteos","kcal":255,"prot":7,"carb":3,"fat":24,"fib":0},
    {"name_pt":"cream cheese","category":"lacteos","kcal":340,"prot":6,"carb":4,"fat":34,"fib":0},
    {"name_pt":"queijo coalho","category":"lacteos","kcal":295,"prot":21,"carb":3,"fat":22,"fib":0},
    {"name_pt":"ricota","category":"lacteos","kcal":140,"prot":11,"carb":3,"fat":9,"fib":0},
    {"name_pt":"queijo prato","category":"lacteos","kcal":360,"prot":22,"carb":2,"fat":29,"fib":0},
    {"name_pt":"abacate","category":"frutas","kcal":160,"prot":2,"carb":9,"fat":15,"fib":7},
    {"name_pt":"abacaxi","category":"frutas","kcal":50,"prot":0.5,"carb":13,"fat":0.1,"fib":1.4},
    {"name_pt":"manga","category":"frutas","kcal":60,"prot":0.8,"carb":15,"fat":0.4,"fib":1.6},
    {"name_pt":"maracujá","category":"frutas","kcal":97,"prot":2.2,"carb":23,"fat":0.7,"fib":11},
    {"name_pt":"morango","category":"frutas","kcal":32,"prot":0.7,"carb":7.7,"fat":0.3,"fib":2},
    {"name_pt":"melancia","category":"frutas","kcal":30,"prot":0.6,"carb":7.5,"fat":0.2,"fib":0.4},
    {"name_pt":"melão","category":"frutas","kcal":34,"prot":0.8,"carb":8,"fat":0.2,"fib":0.9},
    {"name_pt":"uva","category":"frutas","kcal":69,"prot":0.7,"carb":18,"fat":0.2,"fib":0.9},
    {"name_pt":"pera","category":"frutas","kcal":57,"prot":0.4,"carb":15,"fat":0.1,"fib":3.1},
    {"name_pt":"kiwi","category":"frutas","kcal":61,"prot":1.1,"carb":15,"fat":0.5,"fib":3},
    {"name_pt":"granola","category":"cereais","kcal":470,"prot":10,"carb":62,"fat":20,"fib":7},
    {"name_pt":"aveia em flocos","category":"cereais","kcal":390,"prot":14,"carb":67,"fat":7,"fib":9},
    {"name_pt":"chia","category":"sementes","kcal":485,"prot":16,"carb":42,"fat":31,"fib":34},
    {"name_pt":"linhaça","category":"sementes","kcal":495,"prot":19,"carb":29,"fat":34,"fib":27},
    {"name_pt":"castanha do pará","category":"sementes","kcal":645,"prot":14,"carb":15,"fat":63,"fib":7.5},
    {"name_pt":"amêndoa","category":"sementes","kcal":580,"prot":21,"carb":20,"fat":50,"fib":12.5},
    {"name_pt":"pasta de amendoim","category":"sementes","kcal":590,"prot":25,"carb":20,"fat":50,"fib":6},
    {"name_pt":"manteiga","category":"gorduras","kcal":720,"prot":0.6,"carb":0.7,"fat":81,"fib":0},
    {"name_pt":"margarina","category":"gorduras","kcal":600,"prot":0.4,"carb":0.7,"fat":67,"fib":0},
    {"name_pt":"azeite de oliva","category":"gorduras","kcal":884,"prot":0,"carb":0,"fat":100,"fib":0},
    {"name_pt":"óleo de coco","category":"gorduras","kcal":900,"prot":0,"carb":0,"fat":100,"fib":0},
    {"name_pt":"maionese","category":"gorduras","kcal":680,"prot":1,"carb":2.5,"fat":75,"fib":0},
    {"name_pt":"chocolate ao leite","category":"doces","kcal":545,"prot":7.5,"carb":58,"fat":31,"fib":2.5},
    {"name_pt":"chocolate 70%","category":"doces","kcal":600,"prot":8,"carb":35,"fat":45,"fib":11},
    {"name_pt":"brigadeiro","category":"doces","kcal":380,"prot":6,"carb":58,"fat":13,"fib":2},
    {"name_pt":"pudim de leite","category":"doces","kcal":215,"prot":5,"carb":35,"fat":6,"fib":0},
    {"name_pt":"sorvete","category":"doces","kcal":210,"prot":3.5,"carb":24,"fat":11,"fib":0.5}
  ]$aliases$::jsonb;
  v_alias jsonb;
BEGIN
  FOR v_alias IN SELECT * FROM jsonb_array_elements(v_aliases) LOOP
    INSERT INTO food_db (name_pt, category, kcal_per_100g, protein_g, carbs_g, fat_g, fiber_g, country_code, source)
    SELECT
      v_alias->>'name_pt',
      v_alias->>'category',
      (v_alias->>'kcal')::numeric,
      (v_alias->>'prot')::numeric,
      (v_alias->>'carb')::numeric,
      (v_alias->>'fat')::numeric,
      (v_alias->>'fib')::numeric,
      'BR',
      'alias'
    WHERE NOT EXISTS (
      SELECT 1 FROM food_db
       WHERE name_pt = v_alias->>'name_pt' AND country_code = 'BR'
    );
  END LOOP;
END $$;
