-- Establish an explicit trust boundary for canonical nutrition.
-- Rows generated by a language model remain available for forensic review, but
-- they can no longer be returned by the canonical search or attached to new
-- meal logs. Only datasets with an auditable source may set is_verified=true.

ALTER TABLE public.food_db
  ADD COLUMN is_verified boolean NOT NULL DEFAULT true,
  ADD COLUMN source_ref text;

COMMENT ON COLUMN public.food_db.is_verified IS
  'True only when nutrition comes from an auditable dataset or product label. Canonical search excludes false rows.';

COMMENT ON COLUMN public.food_db.source_ref IS
  'Stable row identifier in the upstream dataset or product label revision.';

CREATE UNIQUE INDEX food_db_source_ref_key
  ON public.food_db (source_ref)
  WHERE source_ref IS NOT NULL;

-- GiST supports nearest-neighbour ordering with the pg_trgm distance operator.
-- The previous similarity() predicate scanned the whole table for every item.
CREATE INDEX food_db_verified_name_norm_gist
  ON public.food_db
  USING gist (name_norm gist_trgm_ops)
  WHERE is_verified IS TRUE;

-- Existing rows do not carry a stable upstream row identifier. Quarantine them
-- by default; the product-label rows below are re-verified explicitly and the
-- following migrations replace matching legacy rows from TACO/USDA with data
-- imported directly from the official datasets.
UPDATE public.food_db
SET is_verified = false,
    source_ref = NULL
WHERE source_ref IS NULL;

UPDATE public.food_db
SET is_verified = true,
    source_ref = CASE source
      WHEN 'product_label_yokey_kumis_2026_07_13'
        THEN 'PRODUCT_LABEL:yokey-kumis:2026-07-13'
      WHEN 'nutella_br_official_2026_07_18'
        THEN 'PRODUCT_LABEL:nutella:BR:2026-07-18'
      WHEN 'nutella_us_official_2026_07_18'
        THEN 'PRODUCT_LABEL:nutella:US:2026-07-18'
      ELSE source_ref
    END
WHERE source IN (
  'product_label_yokey_kumis_2026_07_13',
  'nutella_br_official_2026_07_18',
  'nutella_us_official_2026_07_18'
);

-- The only quarantined row referenced by existing meal logs has a direct SR
-- Legacy equivalent. Keep its user-facing alias while replacing its nutrition
-- with the official FDC 173418 values. Historical meal-log values are untouched.
UPDATE public.food_db
SET kcal_per_100g = 350,
    protein_g = 6.15,
    carbs_g = 5.52,
    fat_g = 34.44,
    fiber_g = 0,
    category = 'Dairy and Egg Products',
    source = 'USDA_FDC_SR_LEGACY_2018_ALIAS',
    source_ref = 'FDC:173418:alias:cream-cheese',
    is_verified = true
WHERE country_code = 'US'
  AND name_norm = 'cream cheese'
  AND source = 'USDA_seed_llm';

ALTER TABLE public.food_db
  ALTER COLUMN is_verified SET DEFAULT false;

-- The verified-only search and write barrier are enabled only after the
-- official catalogs and audited aliases have been imported. Keeping that
-- activation in the final migration avoids a partial-catalog window during
-- production rollout.
